<a href="https://colab.research.google.com/github/SwetaSengupta/DS-Unit-1-Sprint-3-Linear-Algebra/blob/master/Sweta_Sengupta__LS_DS_134_Clustering_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K-Means Clustering

# 1) Use the "Breast Cancer Wisconsin (Diagnostic) Data Set" from Kaggle to try and cluster types of cancer cells. 

Here's the original dataset for your reference:

<https://www.kaggle.com/uciml/breast-cancer-wisconsin-data>

## This is a supervised learning dataset

(Because it has **labels** - The "diagnosis" column.)

In [239]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA # You don't necessarily have to use this
from sklearn.cluster import KMeans # You don't necessarily have to use this
from sklearn.preprocessing import StandardScaler # You don't necessarily have to use this

df = pd.read_csv("https://raw.githubusercontent.com/ryanleeallred/datasets/master/Cancer_Cells.csv")
print(df.shape)
df.head()

(569, 33)


id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

## Now it's an unsupervised learning dataset

(Because we've removed the diagnosis label) - Use this version.

In [222]:
df = df.drop('diagnosis', axis=1)
df.head()

id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
0    842302        17.99  ...                  0.11890          NaN
1    842517        20.57  ...                  0.08902          NaN
2  84300903        19.69  ...                  0.08758          NaN
3  84348301        11.42  ...                  0.17300          NaN
4  84358402        20.29  ...                  0.07678          NaN

[5 rows x 32 columns]

## Let's do it!

- You might want to do some data exploration to see if you can find specific columns that will help you find distinct clusters of cells
- You might want to use the elbow method to decide on the number of clusters to use.


In [0]:
 df_new = df.iloc[:,:-1]


In [224]:
# check for null values
df_new.isnull().sum().any()

False

In [0]:
# Perform K-Means Clustering on the Dataset
k = 2
model = KMeans(n_clusters=k, max_iter=5)

In [226]:
# Fit the instantiated model to our sliced dataframe
features = df_new.columns[1:]
model.fit(df_new[features].values)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=5,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [0]:
# Instantiate the sklearn class, and pick a number of clusters.
#my_kmeans = KMeans(n_clusters=4)

In [195]:
# fit the instantiated model to our data.
#my_kmeans.fit(df_new)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [0]:
# Assign clusters back to our dataframe
df_new['cluster']=model.labels_

In [270]:
df_new.head()

id  radius_mean  ...  fractal_dimension_worst  cluster
0    842302        17.99  ...                  0.11890        0
1    842517        20.57  ...                  0.08902        0
2  84300903        19.69  ...                  0.08758        0
3  84348301        11.42  ...                  0.17300        1
4  84358402        20.29  ...                  0.07678        0

[5 rows x 32 columns]

In [0]:
# the labels are the same as the 2 centers.
labels = my_kmeans.labels_

In [0]:
# Get our centroids
centroids = model.cluster_centers_

In [230]:
# turn them into a dataframe
cc = pd.DataFrame(centroids)
cc.head()

0          1           2   ...        27        28        29
0  19.379924  21.694580  128.231298  ...  0.192431  0.311882  0.086165
1  12.556299  18.570365   81.123470  ...  0.091330  0.283554  0.083282

[2 rows x 30 columns]

In [0]:
# Setup some colors for plotting
base_colors = ['r', 'g']
colors = [base_colors[centroid] for centroid in model.labels_]

In [232]:
# Plot the scatter of our points with calculated centroids
fig, ax = plt.subplots(figsize=(7,6))
ax.scatter(df_new[features[0]], df_new[features[1]], c=colors)
ax.scatter(cc[0], cc[1], c='black', s=200);

In [0]:
# Using the elbow method
sum_of_squared_distances = []
K = range(1,15)
for k in K:
    km = KMeans(n_clusters=k)
    km = km.fit(df_new[features].values)
    sum_of_squared_distances.append(km.inertia_)

In [234]:
plt.plot(K, sum_of_squared_distances, 'bx-')
plt.xlabel('k')
plt.ylabel('Sum_of_squared_distances')
plt.title('Elbow Method For Optimal k')
plt.show()

In [235]:
# what's our silhouette score?
from sklearn import metrics
metrics.silhouette_score(df_new, model.labels_, metric='euclidean')

0.18752786323251175

In [236]:
# What is the predicted centroid for each data point?  
model.labels_

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

## Check you work: 

This is something that in a truly unsupervised learning situation **WOULD NOT BE POSSIBLE**. But for educational purposes go back and grab the true diagnosis column (label) from the original dataset. Take your cluster labels and compare them to the original diagnosis column. You can make scatterplots for each to see how they compare or you can calculate a percent accuracy score like: 
\begin{align}
\frac{\text{Num Correct Labels}}{\text{Num Total Observations}}
\end{align}

In [0]:
# Your Code Here

In [300]:
Diag = pd.Series(df['diagnosis'])
Clust = pd.Series(df_new['cluster'])
comp = {'Diagnosis': Diag, 'Cluster': Clust}
compare = pd.DataFrame(comp)
compare_final = compare.replace(to_replace=["M","B"], value=["0","1"])
compare_final

Diagnosis  Cluster
0           0        0
1           0        0
2           0        0
3           0        1
4           0        0
..        ...      ...
564         0        0
565         0        0
566         0        1
567         0        0
568         1        1

[569 rows x 2 columns]

In [305]:
pd.crosstab(compare_final['Cluster'], compare_final['Diagnosis'])

Diagnosis    0    1
Cluster            
0          130    1
1           82  356

# 2) Perform PCA on your dataset first and *then* use k-means clustering. 

- You need to standardize your data before PCA.
- First try clustering just on PC1 and PC2 so that you can make a scatterplot of your clustering.
- Then use use a scree plot to decide how many principal components to include in your clustering, and use however many principal components you need in order to retain 90% of the variation of the original dataset



In [0]:
##### Your Code Here #####

In [81]:
# start by Standardizing the data since PCA's output is influenced based on the scale of the features of the data.
from sklearn.preprocessing import StandardScaler
feature_cols=df_new.columns[1:]
feature_cols[:5]

Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean'],
      dtype='object')

In [0]:
# normalizing the features
x = df_new.loc[:, feature_cols].values
x = StandardScaler().fit_transform(x)

In [83]:
# Let's check whether the normalized data has a mean of zero and a standard deviation of one.
print('{:.2f}'.format(np.mean(x)))
print(np.std(x))

0.00
1.0


In [114]:
# convert the normalized features into a dataframe
df_new_processed = pd.DataFrame(x,columns=feature_cols)
print(df_new_processed.shape)
df_new_processed.head(5)


(569, 30)


radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0     1.097064     -2.073335  ...        2.750622                 1.937015
1     1.829821     -0.353632  ...       -0.243890                 0.281190
2     1.579888      0.456187  ...        1.152255                 0.201391
3    -0.768909      0.253732  ...        6.046041                 4.935010
4     1.750297     -1.151816  ...       -0.868353                -0.397100

[5 rows x 30 columns]

In [0]:
# use the sklearn library to import the PCA module
from sklearn.decomposition import PCA

In [0]:
# instantiate the sklearn class
# pass the desired number of components 
pca_df_new_processed = PCA(n_components=2)

In [0]:
# call fit_transform on the aggregate data
pca_data = pca_df_new_processed.fit_transform(x)

In [308]:
# create a DataFrame that will have 
# the principal component values for all samples
df_now = pd.DataFrame(data = pca_data, columns = ['comp_1', 'comp_2'])
df_now.head()

comp_1     comp_2
0  9.192837   1.948583
1  2.387802  -3.768172
2  5.733896  -1.075174
3  7.122953  10.275589
4  3.935302  -1.948072

In [249]:
# how much variation did each principal component explain?
pca_df_new_processed.explained_variance_ratio_

array([0.44272026, 0.18971182])

In [250]:
# How much total variance did we explain?
sum(pca_df_new_processed.explained_variance_ratio_)

0.6324320765155949

In [251]:
# How much information did we lose?
1-sum(pca_df_new_processed.explained_variance_ratio_)

0.36756792348440515

###now apply clustering

In [0]:
# Initialize an instance of the KMeans class from sklearn.
k =2 
model3 = KMeans(n_clusters=k , max_iter=5)

In [253]:
# Fit the instantiated model to our sliced dataframe
model3.fit(df_now.values)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=5,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [0]:
# Assign predicted clusters back to our dataframe
df_now['cluster'] = model3.labels_

In [0]:
# Get our centroids
centroids = model3.cluster_centers_

In [256]:
# turn them into a dataframe
cc =pd.DataFrame(centroids)
cc

0         1
0  4.358830  0.042977
1 -2.202478 -0.021716

In [0]:
# Setup some colors for plotting
base_colors = ['r', 'g']
colors = [base_colors[centroid] for centroid in model3.labels_]

In [259]:
# Plot the scatter of our points with calculated centroids
fig, ax = plt.subplots(figsize=(7,6))
ax.scatter(df_now['comp_1'], df_now['comp_2'], c=colors)
ax.scatter(cc[0], cc[1], c='black', s=200);

In [260]:
# what's our silhouette score?
from sklearn import metrics
metrics.silhouette_score(df_now, model3.labels_, metric='euclidean')

0.5147831271800967

In [261]:
# What is the predicted centroid for each data point?  
model.labels_

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

## Check your work: 

- Compare your PC1, PC2 clustering scatterplot to the clustering scatterplots you made on the raw data
- Calculate accuracy scores for both the PC1,PC2 Principal component clustering and the 90% of explained variance clustering.

How do your accuracy scores -when preprocessing the data with PCA- compare to the accuracy when simply clustering on the raw data?

In [0]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

In [0]:
scaler = MinMaxScaler(feature_range=[0, 1])
data_rescaled = scaler.fit_transform(df_new)

In [244]:
#Fitting the PCA algorithm with our Data
pca = PCA().fit(data_rescaled)
#Plotting the Cumulative Summation of the Explained Variance
plt.figure()
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('Number of Components')
plt.xticks(np.arange(1,100,5))
plt.ylabel('Variance (%)') #for each component
plt.title('Pulsar Dataset Explained Variance')
plt.show()

In [316]:
#scatterplot for PC1 and PC2
# plot the visualization of the data by the components
plt.figure(figsize=(10,10))
plt.xlabel('Component 1')
plt.ylabel('Component 2')
for k, c in [(0, 'green'), (1, 'gold')]:
    subset=df[df['diagnosis']==k]    
    plt.scatter(x=df_now['comp_1'], 
                y=df_now['comp_2'], 
                s=100,
                alpha=.5,
                color=c,
                label=k);
plt.legend();

# Stretch Goals:

- Study for the Sprint Challenge
- Work on your Data Storytelling Project