<a href="https://colab.research.google.com/github/hadi-M/DS-Unit-1-Sprint-3-Linear-Algebra/blob/master/module1-vectors-and-matrices/HADI_MODARES_LS_DS_131_Vectors_and_Matrices_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1 - Scalars and Vectors

For the questions below it is not sufficient to simply provide answer to the questions, but you must solve the problems and show your work using python (the NumPy library will help a lot!) Translate the vectors and matrices into their appropriate python  representations and use numpy or functions that you write yourself to demonstrate the result or property. 

## 1.1 Create a two-dimensional vector and plot it on a graph

In [0]:
import numpy as np
from matplotlib import pyplot as plt
from pdb import set_trace as st

In [12]:
v1 = np.array([1, 3])
v2 = np.array([4, 5])

fig, ax = plt.subplots()
ax.set_xlim(-1, 7)
ax.set_ylim(-1, 7)

plt.arrow(0, 0, v1[0], v1[1], color="orange", head_width=0.25, head_length=0.25)
plt.arrow(0, 0, v2[0], v2[1], color="cyan", head_width=0.25, head_length=0.25)


plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

AttributeError: ignored

<Figure size 432x288 with 1 Axes>

## 1.2 Create a three-dimensional vecor and plot it on a graph

In [13]:
v_3d = np.array([2, 4, 6])

fig, ax = plt.subplots()
ax = fig.add_subplot(111, projection='3d')

ax.set_xlim([0, 3])
ax.set_ylim([0, 3])
ax.set_zlim([0, 3])
# 
ax.quiver(0, 0, 0, v_3d[0], v_3d[1], v_3d[2], length=0.25);

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

AttributeError: ignored

<Figure size 432x288 with 2 Axes>

## 1.3 Scale the vectors you created in 1.1 by $5$, $\pi$, and $-e$ and plot all four vectors (original + 3 scaled vectors) on a graph. What do you notice about these vectors? 

In [14]:
from math import e, pi
print(e)
print(pi)

fig, ax = plt.subplots()
ax.set_xlim(0, 30)
ax.set_ylim(0, 30)

colors = ["orange", "red", "blue", "green", "purple", "brown"]
index = 0

for vec in (v1, v2):
    for scale in (5, pi, e):
        # st()
        scaled_vec = scale * vec
        plt.arrow(0, 0, scaled_vec[0], scaled_vec[1], head_length=0.25, head_width=0.25, color=colors[index])
        index += 1

2.718281828459045
3.141592653589793


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

AttributeError: ignored

<Figure size 432x288 with 1 Axes>

In [0]:
# the scaled grapphs are parallel to each other

## 1.4 Graph vectors $\vec{a}$ and $\vec{b}$ and plot them on a graph

\begin{align}
\vec{a} = \begin{bmatrix} 5 \\ 7 \end{bmatrix}
\qquad
\vec{b} = \begin{bmatrix} 3 \\4 \end{bmatrix}
\end{align}

In [16]:
a_v = np.array(
    [
     [5],
     [7]
    ]
)

b_v = np.array(
    [
     [3],
     [4]
    ]
)

fig, ax = plt.subplots()

ax.set_xlim(0, 8)
ax.set_ylim(0, 8)

ax.arrow(0, 0, a_v[0][0], a_v[1][0], head_length=0.25, head_width=0.25, color="red");
ax.arrow(0, 0, b_v[0][0], b_v[1][0], head_length=0.25, head_width=0.25, color="blue");


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

AttributeError: ignored

<Figure size 432x288 with 1 Axes>

## 1.5 find $\vec{a} - \vec{b}$ and plot the result on the same graph as $\vec{a}$ and $\vec{b}$. Is there a relationship between vectors $\vec{a} \thinspace, \vec{b} \thinspace \text{and} \thinspace \vec{a-b}$

In [17]:
fig, ax = plt.subplots()

ax.set_xlim(0, 8)
ax.set_ylim(0, 8)

ax.arrow(0, 0, a_v[0][0], a_v[1][0], head_length=0.25, head_width=0.25, color="red");
ax.arrow(0, 0, b_v[0][0], b_v[1][0], head_length=0.25, head_width=0.25, color="blue");

a_minus_b_v = a_v-b_v
ax.arrow(b_v[0][0], b_v[1][0], a_minus_b_v[0][0], a_minus_b_v[1][0], head_length=0.25, head_width=0.25, color="green");

# a-b is a vector that connects end of vector b to end of vector a

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

AttributeError: ignored

<Figure size 432x288 with 1 Axes>

## 1.6 Find $c \cdot d$

\begin{align}
\vec{c} = \begin{bmatrix}7 & 22 & 4 & 16\end{bmatrix}
\qquad
\vec{d} = \begin{bmatrix}12 & 6 & 2 & 9\end{bmatrix}
\end{align}


In [18]:
c_v = np.array([7, 22, 4, 16])
d_v = np.array([12, 6, 2, 9])

np.dot(c_v, d_v)

368

##  1.7 Find $e \times f$

\begin{align}
\vec{e} = \begin{bmatrix} 5 \\ 7 \\ 2 \end{bmatrix}
\qquad
\vec{f} = \begin{bmatrix} 3 \\4 \\ 6 \end{bmatrix}
\end{align}

In [22]:
e_v = np.array([5, 7, 2]).reshape(3, -1)
f_v = np.array([3, 4, 6]).reshape(3, -1)

display(e_v)
display(f_v)

np.cross(e_v, f_v, axis=0)
# np.cross(e_v.reshape(1, -1), f_v.reshape(1, -1))
# e_v.reshape(1, -1)

array([[5],
       [7],
       [2]])

array([[3],
       [4],
       [6]])

array([[ 34],
       [-24],
       [ -1]])

## 1.8 Find $||g||$ and then find $||h||$. Which is longer?

\begin{align}
\vec{g} = \begin{bmatrix} 1 \\ 1 \\ 1 \\ 8 \end{bmatrix}
\qquad
\vec{h} = \begin{bmatrix} 3 \\3 \\ 3 \\ 3 \end{bmatrix}
\end{align}

In [0]:
g_v = np.array([1, 1, 1, 8]).transpose()
h_v = np.array([3, 3, 3, 3, ]).transpose()

display(np.linalg.norm(g_v))
display(np.linalg.norm(h_v))

# therefore g is longer

# Part 2 - Matrices

## 2.1 What are the dimensions of the following matrices? Which of the following can be multiplied together? See if you can find all of the different legal combinations.
\begin{align}
A = \begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
\qquad
B = \begin{bmatrix}
2 & 4 & 6 \\
\end{bmatrix}
\qquad
C = \begin{bmatrix}
9 & 6 & 3 \\
4 & 7 & 11
\end{bmatrix}
\qquad
D = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\qquad
E = \begin{bmatrix}
1 & 3 \\
5 & 7
\end{bmatrix}
\end{align}

In [0]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = np.array(
    [2, 4, 6]
)

C = np.array(
    [
        [9, 6, 3],
        [4, 7, 11]
    ]
)

D = np.array(
    [
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]
    ]
)

E = np.array(
    [
        [1, 3],
        [5, 7]
    ]
)

# A: 3*2
# B: 1*3
# C: 2*3
# D: 3*3
# E: 2*2

# legal combinations:
# A*C, A*E
# B*A, B*D
# C*A, C*D
# D*A, D*D,
# E*C, E*E

## 2.2 Find the following products: CD, AE, and BA. What are the dimensions of the resulting matrices? How does that relate to the dimensions of their factor matrices?

In [0]:
CD = np.matmul(C, D)
AE = np.matmul(A, E)
BA = np.matmul(B, A)
print(
    '''
    CD: {}
    AE: {}
    BA: {}
    '''.format(CD.shape, AE.shape, BA.shape)
    )

## 2.3  Find $F^{T}$. How are the numbers along the main diagonal (top left to bottom right) of the original matrix and its transpose related? What are the dimensions of $F$? What are the dimensions of $F^{T}$?

\begin{align}
F = 
\begin{bmatrix}
20 & 19 & 18 & 17 \\
16 & 15 & 14 & 13 \\
12 & 11 & 10 & 9 \\
8 & 7 & 6 & 5 \\
4 & 3 & 2 & 1
\end{bmatrix}
\end{align}

In [0]:
F = np.array(
    [
        [20 , 19 , 18 , 17],
        [16 , 15 , 14 , 13],
        [12 , 11 , 10 , 9],
        [8 , 7 , 6 , 5],
        [4 , 3 , 2, 1]
    ]
)

Ft = F.transpose()

print("F dim: {}".format(F.shape))
print("F transpos dim: {}".format(Ft.shape))


# Part 3 - Square Matrices

## 3.1 Find $IG$ (be sure to show your work) 😃

You don't have to do anything crazy complicated here to show your work, just create the G matrix as specified below, and a corresponding 2x2 Identity matrix and then multiply them together to show the result. You don't need to write LaTeX or anything like that (unless you want to).

\begin{align}
G= 
\begin{bmatrix}
13 & 14 \\
21 & 12 
\end{bmatrix}
\end{align}

In [0]:
G = np.array(
    [
        [13, 14],
        [21, 12]
    ]
)

I_22 = np.identity(2)

np.matmul(G, I_22)

## 3.2 Find $|H|$ and then find $|J|$.

\begin{align}
H= 
\begin{bmatrix}
12 & 11 \\
7 & 10 
\end{bmatrix}
\qquad
J= 
\begin{bmatrix}
0 & 1 & 2 \\
7 & 10 & 4 \\
3 & 2 & 0
\end{bmatrix}
\end{align}


In [0]:
H = np.array(
    [
        [12, 11],
        [7, 10]
    ]
)

J = np.array(
    [
        [0, 1, 2],
        [7, 10, 4],
        [3, 2, 0]
    ]
)

## 3.3 Find $H^{-1}$ and then find $J^{-1}$

In [0]:
H_inverse = np.linalg.inv(H)
J_inverse = np.linalg.inv(J)
# np.matmul(H_inverse, H)
display(np.matmul(H, H_inverse))
display(np.matmul(J, J_inverse))

## 3.4 Find $HH^{-1}$ and then find $J^{-1}J$. Is $HH^{-1} == J^{-1}J$? Why or Why not? 

Please ignore Python rounding errors. If necessary, format your output so that it rounds to 5 significant digits (the fifth decimal place).

In [0]:
# they are not the same, one is 3x3 and another is 2x2

# Stretch Goals: 

A reminder that these challenges are optional. If you finish your work quickly we welcome you to work on them. If there are other activities that you feel like will help your understanding of the above topics more, feel free to work on that. Topics from the Stretch Goals sections will never end up on Sprint Challenges. You don't have to do these in order, you don't have to do all of them. 

- Write a function that can calculate the dot product of any two vectors of equal length that are passed to it.


In [0]:
def my_dot(v1, v2):
    return sum([v1[i] * v2[i] for i in range(len(v1))])

my_dot(
    [1,2,3],
    [2,2,2]
)


- Write a function that can calculate the norm of any vector


In [0]:
def my_norm(vec):
    return sum([i ** 2 for i in vec]) ** (0.5)

my_norm([1,2,3]) #** 2

- Prove to yourself again that the vectors in 1.9 are orthogonal by graphing them. 
- Research how to plot a 3d graph with animations so that you can make the graph rotate (this will be easier in a local notebook than in google colab)
- Create and plot a matrix on a 2d graph.
- Create and plot a matrix on a 3d graph.
- Plot two vectors that are not collinear on a 2d graph. Calculate the determinant of the 2x2 matrix that these vectors form. How does this determinant relate to the graphical interpretation of the vectors?



In [0]:
%matplotlib widget