# Vertical Line Test

## 1.1 Create two graphs, one that passes the vertical line test and one that does not.

## 1.2 Why are graphs that don't pass the vertical line test not considered "functions?"

###Graphs that don't pass the vertical line test have more than one output for a given input, as shown by choosing a vertical line on x and interceting on more than one y value. 

# Functions as Relations

## 2.1 Which of the following relations are functions? Why?

\begin{align}
\text{Relation 1: } \{(1, 2), (3, 2), (1, 3)\}
\\
\text{Relation 2: } \{(1, 3), (2, 3), (6, 7)\}
\\
\text{Relation 3: } \{(9, 4), (2, 1), (9, 6)\}
\\
\text{Relation 4: } \{(6, 2), (8, 3), (6, 4)\}
\\
\text{Relation 5: } \{(2, 6), (2, 7), (2, 4)\}
\end{align}

# Functions as a mapping between dimensions


## 3.1 for the following functions what is the dimensionality of the domain (input) and codomain (range/output)?

\begin{align}
m(𝑥_1,𝑥_2,𝑥_3)=(x_1+x_2, x_1+x_3, x_2+x_3)
\\
n(𝑥_1,𝑥_2,𝑥_3,𝑥_4)=(x_2^2 + x_3, x_2x_4)
\end{align}

## 3.2 Do you think it's possible to create a function that maps from a lower dimensional space to a higher dimensional space? If so, provide an example.

# Vector Transformations

## 4.1 Plug the corresponding unit vectors into each function. Use the output vectors to create a transformation matrix.

\begin{align}
p(\begin{bmatrix}x_1 \\ x_2 \end{bmatrix}) = \begin{bmatrix} x_1 + 3x_2 \\2 x_2 - x_1 \\  \end{bmatrix}
\\
\\
q(\begin{bmatrix}x_1 \\ x_2 \\ x_3\end{bmatrix}) = \begin{bmatrix} 4x_1 + x_2 + 2x_3 \\2 x_2 - x_1 + 3x_3 \\ 5x_1 - 2x_3 + x_2  \end{bmatrix}
\end{align}

## 4.2 Verify that your transformation matrices are correct by choosing an input matrix and calculating the result both via the traditional functions above and also via vector-matrix multiplication.

# Eigenvalues and Eigenvectors

## 5.1 In your own words, give an explanation for the intuition behind eigenvalues and eigenvectors.

# The Curse of Dimensionality

## 6.1 What are some of the challenges of working with high dimensional spaces?

## 6.2 What is the rule of thumb for how many observations you should have compared to parameters in your model?

# Principal Component Analysis

## 7.1 Code for loading and cleaning the 2013 national dataset from the [Housing Affordability Data System (HADS)](https://www.huduser.gov/portal/datasets/hads/hads.html) --housing data, can be found below. 

## Perform PCA on the processed dataset `national_processed` (Make sure you standardize your data!) and then make a scatterplot of PC1 against PC2. Some of our discussion and work around PCA with this dataset will continue during tomorrow's lecture and assignment.

Not only does this dataset have decent amount columns to begin with (99), but in preparing the data for PCA we have also [one-hot-encoded](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f#targetText=One%20hot%20encoding%20is%20a,the%20entry%20in%20the%20dataset.) all of the categorical variables. This has the effect of creating a new column for each individual category of each categorical variable. After processing this dataset has 64738 columns. --Das a lot of columns.

Don't worry too much about the mechanics of one-hot encoding right now, you will learn and experiment with a whole bunch of categorical encoding approaches in unit 2. 

The code below will read in the dataset and perform the one-hot encoding of the categorical variables. Start adding your PCA code at the bottom of the provided code.

In [12]:
from urllib.request import urlopen
from zipfile import ZipFile
from io import BytesIO
import os.path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read Natinal Data 
national_url = 'https://www.huduser.gov/portal/datasets/hads/hads2013n_ASCII.zip'
national_file = 'thads2013n.txt'

if os.path.exists(national_file):
    national = pd.read_csv(national_file)
else: 
    z_national = urlopen(national_url)
    zip_national = ZipFile(BytesIO(z_national.read())).extract(national_file)
    national = pd.read_csv(zip_national)

print(national.shape)
national.head()

(64535, 99)


CONTROL  AGE1 METRO3  ...          FMTBURDEN  FMTREGION  FMTSTATUS
0  '100003130103'    82    '3'  ...     '2 30% to 50%'       '-5'       '-5'
1  '100006110249'    50    '5'  ...  '1 Less than 30%'       '-5'       '-5'
2  '100006370140'    53    '5'  ...    '3 50% or More'       '-5'       '-5'
3  '100006520140'    67    '5'  ...  '1 Less than 30%'       '-5'       '-5'
4  '100007130148'    26    '1'  ...  '1 Less than 30%'       '-5'       '-5'

[5 rows x 99 columns]

In [13]:
# Look at datatypes
# a lot of object datatypes even though they seem to be strings of numbers.
national.dtypes

CONTROL            object
AGE1                int64
METRO3             object
REGION             object
LMED                int64
                    ...  
FMTINCRELAMICAT    object
FMTASSISTED        object
FMTBURDEN          object
FMTREGION          object
FMTSTATUS          object
Length: 99, dtype: object

In [14]:
# check for null values
national.isnull().sum().any()

False

In [15]:
# check for number of categorical vs numeric columns
cat_cols = national.columns[national.dtypes=='object']
num_cols = national.columns[national.dtypes!='object']

print(f'{len(cat_cols)} categorical columns')
print(f'{len(num_cols)} numerical columns')

32 categorical columns
67 numerical columns


In [16]:
# We're making a copy of our data in case we mess something up.
national_processed = national.copy()

# Categorically Encode our Variables:
# They need to all be numeric before we do PCA.
# https://pbpython.com/categorical-encoding.html

# Cast categorical columns to "category" data type
national_processed[cat_cols] = national_processed[cat_cols].astype('category')

national_processed.dtypes

CONTROL            category
AGE1                  int64
METRO3             category
REGION             category
LMED                  int64
                     ...   
FMTINCRELAMICAT    category
FMTASSISTED        category
FMTBURDEN          category
FMTREGION          category
FMTSTATUS          category
Length: 99, dtype: object

In [17]:
# Replace all category cell values with their numeric category codes
for col in cat_cols:
  national_processed[col] = national_processed[col].cat.codes

print(national_processed.shape)
national_processed.head()

(64535, 99)


CONTROL  AGE1  METRO3  REGION  ...  FMTASSISTED  FMTBURDEN  FMTREGION  FMTSTATUS
0        0    82       2       0  ...            0          2          0          0
1        1    50       4       2  ...            0          1          0          0
2        2    53       4       2  ...            0          3          0          0
3        3    67       4       2  ...            0          1          0          0
4        4    26       0       2  ...            1          1          0          0

[5 rows x 99 columns]

In [18]:
# Now we only ahve numeric columns (ints and floats)
national_processed.dtypes

CONTROL            int32
AGE1               int64
METRO3              int8
REGION              int8
LMED               int64
                   ...  
FMTINCRELAMICAT     int8
FMTASSISTED         int8
FMTBURDEN           int8
FMTREGION           int8
FMTSTATUS           int8
Length: 99, dtype: object

In [19]:
### Your Code Here
#standardizing the data so that it has a mean of 0 and an std of 1 for PCA to work properly 
from sklearn.preprocessing import StandardScaler
x = national_processed.values
x[0]

array([ 0.00000000e+00,  8.20000000e+01,  2.00000000e+00,  0.00000000e+00,
        7.37380000e+04,  9.56000000e+02,  1.57380000e+04,  2.62130000e+04,
        4.03220000e+04,  1.10670000e+04,  2.00000000e+00,  2.00600000e+03,
        0.00000000e+00,  1.00000000e+00,  4.00000000e+04, -6.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  6.00000000e+00,  3.11739424e+03,
        1.00000000e+00,  1.80210000e+04,  1.00000000e+00,  5.33000000e+02,
        1.00000000e+00,  0.00000000e+00,  1.69000000e+02,  2.13750000e+02,
        6.48588189e+02,  8.03050535e+02,  6.96905247e+02,  6.15156712e+02,
        0.00000000e+00, -9.00000000e+00,  7.37380000e+04,  1.57380000e+04,
        2.62130000e+04,  4.03220000e+04,  5.16166000e+04,  2.02345714e+04,
        3.37024286e+04,  5.18425714e+04,  6.63642000e+04,  3.54919261e-01,
        3.49131868e+01,  2.00000000e+00,  1.62835457e+02,  3.00000000e+00,
        4.71260460e+01,  1.00000000e+00,  3.90926547e+01,  2.00000000e+00,
        2.34422405e+02,  

In [20]:
#running standard scalar to get a mean of 0 and std of 1 
x = StandardScaler().fit_transform(x)
x[0]

array([-1.73202397e+00,  1.48807451e+00,  6.08784190e-01, -1.32787201e+00,
        4.54952606e-01, -5.28765921e-01, -4.44469676e-01, -4.45261523e-01,
       -5.53127065e-01, -6.81428626e-01, -6.03699689e-01,  1.50419630e+00,
       -2.71748561e-01, -1.42291570e-01, -4.09727648e-01, -2.68140138e-01,
       -5.18234441e-01, -2.53700793e-01,  1.93640615e-01,  9.89255906e-01,
       -3.45248174e-01, -5.82420511e-01, -1.18867396e-03, -5.38156902e-01,
       -6.26460033e-01, -8.58681410e-01, -1.08317796e-01,  1.00240345e+00,
       -5.24571903e-01, -4.89431200e-01, -5.11001887e-01, -5.35753189e-01,
       -6.93001039e-01, -7.74303458e-01,  4.54952606e-01, -4.44469676e-01,
       -4.45261523e-01, -5.53127065e-01, -1.00275544e-01, -1.39349122e-01,
       -1.40598232e-01, -2.40163048e-01, -5.21149570e-02, -1.47236120e-02,
       -5.66455224e-01, -3.37128482e-01, -4.55410748e-01,  2.19280365e-01,
       -5.58773426e-01, -1.56587865e-01, -5.68400718e-01, -9.56874202e-01,
       -2.79520779e-01,  

In [22]:
#testing that this actually worked
print('{:.2f}'.format(np.mean(x)))
print('{:.2f}'.format(np.std(x)))

0.00
0.99


In [0]:
#importing pca from sklearn
from sklearn.decomposition import PCA

In [0]:
#instantiating pca for use 
pca_national = PCA(n_components=2)

In [25]:
# fitting and transforming the data
pca_data = pca_national.fit_transform(x)
pca_data

array([[-2.57657018, -1.37612737],
       [ 2.04064284, -0.98806145],
       [ 1.21527025,  0.37016815],
       ...,
       [ 1.83162816, -2.9557021 ],
       [-5.02514474, -2.52857813],
       [-9.89816404, -0.80284266]])

In [26]:
#turning it into a dataframe 
pca_nat_df = pd.DataFrame(data=pca_data, columns=['PC1', 'PC2'])
pca_nat_df

PC1       PC2
0     -2.576570 -1.376127
1      2.040643 -0.988061
2      1.215270  0.370168
3      2.821837  1.723711
4     -1.570106 -0.878362
...         ...       ...
64530 -3.052490  0.413172
64531 -6.533380 -5.274883
64532  1.831628 -2.955702
64533 -5.025145 -2.528578
64534 -9.898164 -0.802843

[64535 rows x 2 columns]

In [27]:
#checking how much variation that the pca explained 
sum(pca_national.explained_variance_ratio_)

0.48492705197480007

In [28]:
#how much variation we missed 
1 - sum(pca_national.explained_variance_ratio_)

0.5150729480251999

In [0]:
#plotting a scatter plot between the two components 
import matplotlib.pyplot as plt
fig, ax = plt.subplot()
fig.figsize()

# Stretch Goals

## 1) Perform further data exploration on the HADS national dataset (the version before we one-hot encoded it) Make scatterplots and see if you can see any resemblance between the original scatterplots and the plot of the principal components that you made in 7.1. 

(You may or may not not see very much resemblance depending on the variables you choose, and that's ok!)

## 2) Study "Scree Plots" and then try and make one for your PCA dataset. How many principal conponents do you need to retain in order for your PCs to contain 90% of the explained variance? 

We will present this topic formally at the beginning of tomorrow's lecture, so if you figure this stretch goal out, you're ahead of the game. 

## 3) Explore further the intuition behind eigenvalues and eigenvectors by creating your very own eigenfaces:

Prioritize self-study over this stretch goal if you are not semi-comfortable with the topics of PCA, Eigenvalues, and Eigenvectors.

![Eigenfaces](https://i.pinimg.com/236x/1c/f1/01/1cf101a9859437a5d096a04b05be06b4--faces-tattoo.jpg)

You don't necessarily have to use this resource, but this will get you started: 
[Eigenface Tutorial](https://sandipanweb.wordpress.com/2018/01/06/eigenfaces-and-a-simple-face-detector-with-pca-svd-in-python/)